name: Go CLI
on:
    push:
        branches: [ main ]
        tags: 
            -   'v*.*.*'
    pull_request: 
        branches: [ main ]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Setup GO
                uses: actions/setup-go@v5
                with: 
                    go-version: '1.24'
            -   name: Download deps...
                run: go mod tidy
            -   name: Run tests...
                run: go test ./... -v -coverprofile=coverage.out
            -   name: Lint code
                run: go vet ./...
            -   name: Upload Test Coverage (artifact)
                uses: actions/upload-artifact@v4
                with:
                    name: coverage
                    path: coverage.out

    release:
        runs-on: ubuntu-latest
        name: Create GITHUB release
        needs: test
        if: startsWith(github.ref,'refs/tags/v')
        steps:
            -   name: checkout code
                uses: actions/checkout@v4
            -   name: Set up GO
                uses: actions/setup-go@v5
                with: 
                    go-version: '1.24'
            -   name: Build (verify build success)
                run: go build ./...
            -   name: Generate change log from commits
                id: changelog
                run: | 
                    echo "CHANGELOG=$(git log -1 --pretty=format:"%h - %s (%an)")" >> $GITHUB_ENV
                
            -   name: Create GITHUB release
                uses: softprops/action-gh-release@v2
                with:
                    body: |
                        **Go Module Release**
                        Version: ${{ github.ref_name }}
                        Commit: ${{ github.sha }}

                        **Changelog:**
                        ${{ env.CHANGELOG }}
                env: 
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
